services:
  fastapi:
    restart: always
    build: .
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
    # command: fastapi run src/api/app.py
    command: fastapi dev src/api/app.py --host 0.0.0.0 --port 3000

  interex:
    restart: always
    build: ./frontend
    volumes:
      - ./frontend/src/:/frontend/src/
    env_file:
      - .env
      - ./frontend/.env
    expose:
      - 3001
    command: bash -c "if [ \"$${ENV}\" = \"dev\" ]; then
                        pnpm dev --host --port 3001;
                      else
                        pnpm build && PORT=3001 node build --env-file=.env build;
                      fi"

  nginx:
    restart: always
    build: ./nginx
    expose:
      - 3002
    environment:
      - VIRTUAL_HOST=interex.charlieavery.site
    depends_on:
      - interex
      - fastapi
