services:
  fastapi:
    build: .
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - ./src:/app/src
    # command: fastapi run src/api/app.py
    command: fastapi dev src/api/app.py --host 0.0.0.0 --port 8080

  sveltekit:
    restart: always
    # env_file:
      # - .env
    build: ./frontend
    # command: node -r dotenv/config build
    # command: node build
    command: pnpm dev --host
    expose:
      - 5173
    volumes:
      - ./frontend/src/:/frontend/src/
    env_file:
      - ./frontend/.env

  nginx:
    restart: always
    build: ./nginx
    ports:
      - 5173:5173
    depends_on:
      - sveltekit
      - fastapi
