name: Test
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install requirements
        run: uv sync --all-extras --dev

      - name: Define a cache for the virtual environment based on the dependencies lock file
        uses: actions/cache@v4
        with:
          path: /tmp/.uv-cache
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}

      - name: Run the automated tests
        run: uv run pytest -v

      - name: Minimize uv cache
        run: uv cache prune --ci