name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install requirements
        run: uv sync --all-extras --dev

      - name: Run linter
        run: uv run ruff check .

      - name: Run type check
        run: uv run pyright

      - name: Run the automated tests
        run: uv run pytest -v
